export const COLORS = [
  { id: "mocha", hex: "#a47864" },
  { id: "butter", hex: "#f0d78c" },
  { id: "sage", hex: "#879f76" },
  { id: "terracotta", hex: "#c65d3b" },
  { id: "chocolate", hex: "#4a2c1a" },
  { id: "lavender", hex: "#b8a9c9" },
  { id: "oat", hex: "#d4c4a8" },
  { id: "eucalyptus", hex: "#5f7a6a" },
  { id: "blush", hex: "#e8b4b8" },
  { id: "caramel", hex: "#c68a4e" },
  { id: "dustyblue", hex: "#7a9bb5" },
  { id: "olive", hex: "#6b7042" },
  { id: "indigo", hex: "#3d4f7c" },
  { id: "rose", hex: "#dab2ba" },
  { id: "fig", hex: "#522c40" },
  { id: "cranberry", hex: "#8e2436" },
];
